### ISSUE TITLE
Gmail integration TypeError: Cannot read property 'assertQueue' of undefined in messageBroker.js

### ISSUE THREAD

**Issue by karser** [erxes/erxes-integrations#116]
**Describe the bug**

```
erxes-integrations_1  | 2020-06-24T18:55:48.177Z erxes-integrations:integrations 
erxes-integrations_1  |         Receiving /gmaillogin request from undefined
erxes-integrations_1  |         body: {}
erxes-integrations_1  |         queryParams: {"kind":"gmail","userId":"<id>"}
erxes-integrations_1  |     
erxes-integrations_1  | 2020-06-24T18:55:48.181Z erxes-integrations:gmail 
erxes-integrations_1  |         Receiving /gmaillogin request from undefined
erxes-integrations_1  |         body: {}
erxes-integrations_1  |         queryParams: {"kind":"gmail","userId":"<id>"}
erxes-integrations_1  |     
erxes-integrations_1  | 2020-06-24T18:55:48.183Z erxes-integrations:gmail Google OAuthClient generate auth url
erxes-integrations_1  | 2020-06-24T18:55:48.189Z erxes-integrations:gmail Google OAuthClient failed to generate auth url
erxes-integrations_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'assertQueue' of undefined
erxes-integrations_1  |     at /erxes-integrations/dist/messageBroker.js:118:36
erxes-integrations_1  |     at new Promise (<anonymous>)
erxes-integrations_1  |     at /erxes-integrations/dist/messageBroker.js:116:42
erxes-integrations_1  |     at step (/erxes-integrations/dist/messageBroker.js:33:23)
erxes-integrations_1  |     at Object.next (/erxes-integrations/dist/messageBroker.js:14:53)
erxes-integrations_1  |     at /erxes-integrations/dist/messageBroker.js:8:71
erxes-integrations_1  |     at new Promise (<anonymous>)
erxes-integrations_1  |     at __awaiter (/erxes-integrations/dist/messageBroker.js:4:12)
erxes-integrations_1  |     at Object.exports.sendRPCMessage (/erxes-integrations/dist/messageBroker.js:112:54)
erxes-integrations_1  |     at /erxes-integrations/dist/utils.js:210:58
erxes-integrations_1  |     at step (/erxes-integrations/dist/utils.js:44:23)
erxes-integrations_1  |     at Object.next (/erxes-integrations/dist/utils.js:25:53)
erxes-integrations_1  |     at /erxes-integrations/dist/utils.js:19:71
erxes-integrations_1  |     at new Promise (<anonymous>)
erxes-integrations_1  |     at __awaiter (/erxes-integrations/dist/utils.js:15:12)
erxes-integrations_1  |     at Object.exports.getCommonGoogleConfigs (/erxes-integrations/dist/utils.js:206:55)
erxes-integrations_1  |     at /erxes-integrations/dist/gmail/util.js:218:50
erxes-integrations_1  |     at step (/erxes-integrations/dist/gmail/util.js:44:23)
erxes-integrations_1  |     at Object.next (/erxes-integrations/dist/gmail/util.js:25:53)
erxes-integrations_1  |     at /erxes-integrations/dist/gmail/util.js:19:71
erxes-integrations_1  |     at new Promise (<anonymous>)
erxes-integrations_1  |     at __awaiter (/erxes-integrations/dist/gmail/util.js:15:12)
erxes-integrations_1  |     at Object.exports.getGoogleConfigs (/erxes-integrations/dist/gmail/util.js:214:49)
erxes-integrations_1  |     at /erxes-integrations/dist/gmail/api.js:54:49
erxes-integrations_1  |     at step (/erxes-integrations/dist/gmail/api.js:33:23)
erxes-integrations_1  |     at Object.next (/erxes-integrations/dist/gmail/api.js:14:53)
erxes-integrations_1  |     at /erxes-integrations/dist/gmail/api.js:8:71
erxes-integrations_1  |     at new Promise (<anonymous>)
erxes-integrations_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
erxes-integrations_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Go to AppStore and click Add Gmail integration
2. Enter name, brand and click `Sign in with google`
3. See error in `docker-compose logs -f`

**Expected behavior**
Redirect to google oauth

**Screenshots**
![image](https://user-images.githubusercontent.com/1675033/85617521-0f6ee000-b668-11ea-90d7-f626a5e01dc1.png)

**Context (please include the related information if applicable):**
 - OS: Ubuntu 18.04
 - Browser version: brave
 - erxes v0.14.1, erxes-api v0.14.3, erxes-integrations v0.14.1
 - installation type: docker

**Additional context**
I have followed through [google](https://www.erxes.org/administrator/system-config/#google) and [gmail](https://www.erxes.org/administrator/system-config#gmail) manuals.

**Comment by munkhorgil** [comment]
Hello @karser, Did you add an account  and select it before creating integration?

**Comment by karser** [comment]
Thanks for your response @munkhorgil 
Did you mean LINKED ACCOUNT from the screenshot? I didn't select it because it's empty. I thought `Sign in with Google` button was supposed to add one. How can I add an account then?

**Comment by munkhorgil** [comment]
Yes, you're right you need to add account through Sign in With Google button, can you show me your system config of your Google and Gmail?

**Comment by karser** [comment]
I have filled them in according to the [google](https://www.erxes.org/administrator/system-config/#google) and [gmail](https://www.erxes.org/administrator/system-config#gmail) manuals.

Also, I duplicated them using ENV variables. Here is the relevant part of my docker-compose config:
```
    erxes-api:
        image: erxes/erxes-api:0.14.3
        environment:
            RABBITMQ_HOST: 'amqp://admin:pass@my-domain.com:5672/erxes'
            #..... irrelevant stuff
            # Google Cloud Storage
            GOOGLE_CLIENT_ID: '*****.apps.googleusercontent.com'
            GOOGLE_CLIENT_SECRET: '*****'
            GOOGLE_APPLICATION_CREDENTIALS: './google_cred.json'
            GOOGLE_PROJECT_ID: 'erxes-*****'

    erxes-integrations:
        image: erxes/erxes-integrations:0.14.1
        environment:
            RABBITMQ_HOST: 'amqp://admin:pass@my-domain.com:5672/erxes'
            #..... irrelevant stuff
            # Gmail
            GOOGLE_PROJECT_ID: 'erxes-*****'
            GOOGLE_GMAIL_TOPIC: "erxes-gmail"
            GOOGLE_APPLICATION_CREDENTIALS: './google_cred.json'
            GOOGLE_GMAIL_SUBSCRIPTION_NAME: "erxes-gmail"
            GOOGLE_CLIENT_ID: '*****.apps.googleusercontent.com'
            GOOGLE_CLIENT_SECRET: ''*****'
```

**Comment by karser** [comment]
The problem was in `rabbitmq: { condition: service_started }` which has to be `service_healthy`. So that erxes-integrations was trying to connect to not-yet-ready rabbitmq.
Now it works:                
```
    erxes-integrations:
        image: erxes/erxes-integrations:0.15.4
        depends_on:
            mongo:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
```
